# _config.yml

title: "Yoshua ExcLipsE Blog"
description: "My GitHub Pages blog"
# GitHub Pages 기본 테마 예시 (원하는 테마명으로 교체)
theme: jekyll-theme-primer

# (옵션) GitHub Pages에서 권장되는 플러그인
plugins:
  - jekyll-feed
  - jekyll-seo-tag
